### PR TITLE
Feature/#118 file readbackwards

### PR DESCRIPTION
**Pull request by keedi**
This PR is for #118 issue.

If `count` option is negative number then it acts like Unix `tail`. Unlike [File::ReadBackwards](https://metacpan.org/pod/File::ReadBackwards), it returns last N lines in order as they were in file.

I used buffer size as `BUFSIZ` which is in `stdio.h` but can't convinced it is proper or not. I referenced coreutils's `tail` source code and `BUFSIZ` is used for buffer size, so I used the same value using `POSIX::BUFSIZ()`. On my 64-bit linux machine, it is 8192 and on 32-bit MS Windows XP machine, it is 512. If you think this is not proper value in Perl, please modify it.

http://git.savannah.gnu.org/cgit/coreutils.git/tree/src/tail.c#n473

And I added some test but it may not be sufficient. :)

### CODE REVIEW

**Comment by dagolden** [comment]
I appreciate the work on this.  After reviewing it, I think I'm not going to apply it.  The positive -- at least for me -- is that seeing an implementation gives me some clearer reasons for being uncomfortable about #118.  It also gave me an idea for a simple -- if less efficient approach.

So a few of my reactions to this PR:
* That winds up needing a lot of code for what is likely a rarely-used feature
* It requires pulling in modules (e.g. POSIX), which would bloat memory usage beyond what I consider to still be "::Tiny"
* Reading bytes from an arbitrary point could easily read from the middle of a UTF-8 encoded character, which could cause a fatal error with a strict IO layer. Working around that (catching such errors or switching to raw mode for the seek and then back after) adds even more complexity.

Instead, I'm going to keep your tests (yay!) and implement a little tweak that reads the whole file for negative count but only returns the last N lines.  (Your tests even caught bug in my first attempt, so thank you very much for writing good tests!)

**Comment by dagolden** [comment]
My implementation here: 1e2658a6fb23134370e2842f2105a13ed678b2a1

I left your work in the commit history in case anyone wants to see it.

**Comment by keedi** [comment]
I think accurate approach is better rather than fast but unclear approach. So, I like this simple way.

But I'm afraid it could consume too much memory if someone doesn't want to all contents of large file. So, how about this?

```diff
diff --git a/lib/Path/Tiny.pm b/lib/Path/Tiny.pm
index 0000340..e89fc52 100644
--- a/lib/Path/Tiny.pm
+++ b/lib/Path/Tiny.pm
@@ -1037,15 +1037,13 @@ sub lines {
         my ( @result, $counter );
         while ( my $line = <$fh> ) {
             $line =~ s/(?:\x{0d}?\x{0a}|\x{0d})$// if $chomp;
+            # do not save all lines if count is negative
+            shift @result if $args->{count} < 0 && -$args->{count} <= @result;
             push @result, $line;
             # if count is negative, we read all lines
             last if ++$counter == $args->{count};
         }
-        return (
-            ( $args->{count} > 0 || -$args->{count} > @result )
-            ? @result
-            : @result[ $args->{count} .. -1 ]
-        );
+        return @result;
     }
     elsif ($chomp) {
         return map { s/(?:\x{0d}?\x{0a}|\x{0d})$//; $_ } <$fh>; ## no critic
```

Thanks!

**Comment by dagolden** [comment]
I considered that, but I'm worried that all the extra array manipulation will have a big performance hit.  With push, Perl's array resizing amortizes really well.  But with shift, it either won't really reclaim or will have to rotate pointers.

If someone wants that last few lines of an enormous file and doesn't have a lot of memory, I'm OK with them finding a different tool than Path::Tiny.

But maybe we should benchmark. ☺

**Comment by keedi** [comment]
Thanks for fast response. I read these posts and I think `unshift` is not slow anymore after Perl v5.8. :-)

- [Shift, Pop, Unshift and Push with Impunity!](http://www.perlmonks.org/?node_id=17890)
- [Speeding up unshift](http://www.perlmonks.org/?node_id=42912)

[perl58delta](https://metacpan.org/pod/distribution/perl/pod/perl58delta.pod) document says:

> unshift() should now be noticeably faster.

**Comment by keedi** [comment]
Sorry for the bothering.

I've just checked `av.c` file, and `av_pop()` and `av_shift()` looks almost same.  They just remove the first/last item then decrease size of the array.  Against our expectations, `shift` doesn't seem to move all items to left.

Please let me know if there is anything I mis-understand about `shift`. :)

- [Perl-5.8.8 av_pop](https://github.com/Perl/perl5/blob/perl-5.8.8/av.c#L558)
- [Perl-5.8.8 av_shift](https://github.com/Perl/perl5/blob/perl-5.8.8/av.c#L675)

- [Perl-5.20.2 av_pop](https://github.com/Perl/perl5/blob/v5.20.2/av.c#L584)
- [Perl-5.20.2 av_shift](https://github.com/Perl/perl5/blob/v5.20.2/av.c#L710)

**Comment by dagolden** [comment]
Zefram suggested something even better: a ring buffer

See 6c809df4f596693746d6e0f67aa7a4df910e81af

**Pull request closed without merging**
