### PR TITLE
Rewrite digest algorithm in doc and tests from MD5 to SHA3-256 …

### PR DESCRIPTION
**Pull request by michal-josef-spacek**

### CODE REVIEW

**Comment by karenetheridge** [comment]
but why?

**Comment by xdg** [comment]
Sorry, but I can't accept this.  First, Digest::SHA3 is not in the Perl core.  Second, the reason for Digest::MD5 in tests is because that module was in the Perl core in 5.8 and Digest::SHA was not added to Perl core until 5.10.  So to make tests compatible back to 5.8 without external dependencies, the tests use MD5.

**Comment by michal-josef-spacek** [comment]
@karenetheridge ok, that's good question.
I am working as packager for Fedora, RHEL and there are some consequences to not use algortithms like MD5 (security).
@xdg has good point about upstream dependencies.

I am proposing change this PR in way:
* Use SHA-512 in eval (is in Digest::SHA from perl-5.10.0)
* If eval will not run use MD5.
* Do test for Digest module which is ok.
* Then i could package this dist in way that i will focus to use Digest-SHA only.
* Update doc from this PR (it's nothing about dependencies)

Are you ok with this proposal?

**Comment by xdg** [comment]
What is your actual requirement regarding security from a packaging perspective and what is the documentation behind that?  There is no actual end-user security risk involved in Path::Tiny using MD5 in its own testing suite or having the characters "MD5" in documentation.

**Comment by ap** [comment]
@xdg: maybe update just the docs? I can see an infinitesimal case for that, in that people who know to use MD5 instead of a SHA algorithm when it’s appropriate will know to apply that to docs pointing in a different direction, whereas people who don’t know better would be better served by docs pointing them in a more contemporary direction. And tactically, updating the docs this way might avert some attention from the use of MD5 buried down below in the tests…

The tests should stay as they are, absent a technical rationale.

**Comment by xdg** [comment]
Updating the docs is no big deal, but I'd like to see the actual packaging policy requirements on this before I agree to any change.

**Comment by michal-josef-spacek** [comment]
@xdg Our real situation:
1) We are packaging dist and dist-tests (as extra package) for testing after instalation actually. This mean that dist-test package has dependecy to Digest::MD5.
2) We are going to situation when we want to control these kind of algorithms by configuration. This is for bigger discussion, e.g. in FIPS mode MD5 doesn't work. This mean, that 1) doesn't work. (BTW: actually situation with Perl isn't in this way)

And my suggestion is to move things forward (don't use MD5 if possible).

**Comment by xdg** [comment]
I have no interest in making changes for a theoretical future in which someone attempts FIPS-mode Perl.  If someone intends to do sufficient work to make that happen, patching Path::Tiny's tests will be the least of their challenges.

**Pull request closed without merging**
