### PR TITLE
spew - moved symlink resolution to before tmpfile

### PR DESCRIPTION
**Pull request by markwellis**
to fix can't spew across filesystem boundaries

### CODE REVIEW

**Comment by markwellis** [comment]
have you seen this @xdg, i'm not sure if you have because of your name change

**Comment by xdg** [comment]
I had not, which is odd.  I thought changing dagolden to an organization would turn on notification for the new owner account, but apparently not.  I'll have to find a way to do that programmatically.

Thanks for the PR.  I'll aim to get to it this week.

**Comment by markwellis** [comment]
thought as much. github is an odd one when it comes to notifications!

cheers :)

**Comment by xdg** [comment]
Fixed it with ingy's [git-hub](https://github.com/ingydotnet/git-hub) tool:

```
$ git hub repos -r dagolden | git hub watch -
You are watching 'dagolden/Path-Tiny'
You are watching 'dagolden/Dist-Zilla-Plugin-Test-ReportPrereqs'
You are watching 'dagolden/dancer2-session-json'
You are watching 'dagolden/Dist-Zilla'
You are watching 'dagolden/Path-Iterator-Rule'
...(250+ more repos)...
```

**Pull request merged**
