### PR TITLE
Fix some minor typos

### PR DESCRIPTION
**Pull request by yoshikazusawa**
I found a few small minor typos, so I'll send this patch.

### CODE REVIEW

**Comment by ap** [comment]
I like this but would personally be inclined to throw in a
````perl
*_replacment_path = \&_replacement_path; # backcompat shim
````
just in case anyone is calling this method, despite the fact that it’s private and undocumented. Or alternatively at least call out the rename in the changelog.

**Comment by ap** [comment]
I like this but would personally be inclined to throw in a
````perl
*_replacment_path = \&_replacement_path; # backcompat shim
````
just in case anyone is calling this method, despite the fact that it’s private and undocumented. Or alternatively at least call out the rename in the changelog. @xdg?

**Comment by xdg** [comment]
I'm fine without the shim.  Thank you for the PR.

**Comment by yoshikazusawa** [comment]
@ap Thank you for your suggestion!
@xdg Thank you!

**Pull request merged**
